import turtle

turtle.pencolor('red')
turtle.pensize(5)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.penup()
turtle.left(90)
turtle.forward(100)
turtle.pendown()
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.penup()
turtle.forward(100)
turtle.pendown()
turtle.left(90)
turtle.forward(100)
turtle.exitonclick()

